### ISSUE TITLE
Description layout issue when use with Issue Template plugin

### ISSUE THREAD

**Issue by LeGiangAnh** [akabekobeko/redmine-theme-minimalflat2#82] opened 2016-08-08 04:22 UTC
Hi,

I'm using your theme with [Issue Template](https://github.com/akiko-pusu/redmine_issue_templates) plugin. I defined the template for Bug tracker and didn't define for Feedback and Task.
When I view Bug tracker, the layout of description shows correctly but if I switch to Feedback ore Task, it scaled down.
![image](https://cloud.githubusercontent.com/assets/5027251/17469240/55a6131a-5d5a-11e6-9b59-91648d7d5b63.png)
![image](https://cloud.githubusercontent.com/assets/5027251/17469244/5a98d204-5d5a-11e6-8712-6c1d6d8bfe70.png)

Could you please help me?

Thanks.

**Comment by akabekobeko** [comment] 2016-09-20 02:30
Although tried to install the [Vagrant box onozaty/redmine-3.3](https://atlas.hashicorp.com/onozaty/boxes/redmine-3.3) the [akiko-pusu/redmine_issue_templates](https://github.com/akiko-pusu/redmine_issue_templates) v0.1.3 will be error in the `rake` command.

The `README` of this plug-in has the following description.

> Plugin to generate and use issue templates for each project to assist issue creation. For Redmine 2.1.x or higher, please use version 0.0.4 or higher. For Redmine 2.0, please use version 0.0.3 or higher.

`minimalflat2` supports only the most recent of Redmin. Therefore support of plugins that do not work with Redmine v3.3 is difficult.

**Comment by iquiw** [comment] 2017-08-31 14:51
I think Issue Templates plugin does support Redmine v3.x. At least, it was released recently.

I am using both Issue Templates plugin and minimalflat2 theme, and see no problem.

![with-template](https://user-images.githubusercontent.com/238681/29929604-ec00586a-8ea6-11e7-8b8d-d27b133265d4.png)

![without-template](https://user-images.githubusercontent.com/238681/29929654-06f94c6c-8ea7-11e7-879d-9e851703b7a1.png)

**Comment by akabekobeko** [comment] 2017-09-06 05:43
@iquiw 

Thank you for the report. Since it is said that there is no problem in combination with Redmine 3.x we will close the issue.

**Comment by akabekobeko** [comment] 2017-09-06 06:00
I reopen it because I have not confirmed it in my environment.

**Comment by akabekobeko** [comment] 2017-09-06 06:11
Memo: How to install plugin with [Vagrant box onozaty/redmine-3.4](https://app.vagrantup.com/onozaty/boxes/redmine-3.4)

1. `vagrant up`
2. `vagrant ssh`
3. `cd /var/lib/redmin/plugins`
4. `sudo wget https://github.com/akiko-pusu/redmine_issue_templates/archive/0.1.8.zip`
5. `sudo unzip 0.1.8.zip`
6. `sudo mv redmine_issue_templates-0.1.8/ redmine_issue_templates`
7. `sudo chown -R apache:apache redmine_issue_templates/`
8. `cd /var/lib/redmin`
9. `sudo /usr/local/bin/bundle exec rake redmine:plugins:migrate RAILS_ENV=production`
10. `cd tmp/`
11. `sudo touch restart.txt`
12. `sudo chown apache:apache restart.txt`
13. Access Redmine with a Web browser

**Comment by akabekobeko** [comment] 2017-09-06 06:19
I confirmed that it works normally in my environment (Redmine v3.4 & Issue Templates Plugins v0.1.8), so close the issue.

* Template is applied normally
* `textarea` will be normal even if select tracker (disable template) after applying Template

**Closed by akabekobeko** 2017-09-06 06:19 UTC
Labels: bug
